services:
  sphere_web_dev:
    build:
      context: .
      target: sphere_web_dev
    container_name: sphere_web_dev
    ports:
      - 4201:4200
    env_file: .env
    volumes:
      - "./:/app"
    networks:
      - sphere_net
    command: sh -c "ng serve --host 0.0.0.0 --port 4200 --poll 3000"
    #command: tail -f /dev/null

networks:
  sphere_net:
