services:
  angular:
    build:
      context: .
      target: web_dev
    image: admin_web:v1
    container_name: admin_web
    ports:
      - 4201:4200
    environment:
      API_HOST: django:8000
    volumes:
      - "/app/node_modules"
      - "./:/app"
    networks:
      - admin_net
    command: sh -c "ng serve --host 0.0.0.0 --port 4200 --poll 3000"
    #command: tail -f /dev/null

  angular_prod:
    build:
      context: .
      target: prod
    image: admin_web_prod:v1
    container_name: admin_web_prod
    ports:
      - 80:80
    environment:
      API_HOST: django:8000
    networks:
      - admin_net
    command: sh -c "nginx -g 'daemon off;'"

  angular_build:
    build:
      context: .
      target: build
    command: tail -f /dev/null

networks:
  admin_net:
